# Generated by Django 4.1.3 on 2022-11-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timespend',
            name='punchin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timespend',
            name='punchout',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
